### ISSUE TITLE
Clarify the scope of nostd

### ISSUE THREAD

**Issue by reyang** [open-telemetry/opentelemetry-cpp#134]
In OpenTelemetry C++ we've introduced `nostd` for [ABI compatibility](#37), basically everything exposed by the API package will not have dependency on `std::*` types and C++ exceptions, as none of them would give ABI compatibility guarantee.

To keep the project manageable, we would need to avoid pitfalls such like maintaining a complete set of C++ standard library, or implement a subset and eventually drift away from the standard. This issue serves the purpose of listing the nostd types that we introduced, and the reason why we need them.

### nostd::variant

**Comment by pyohannes** [comment]
We don't have `nostd::pair` yet. Here are the motivations for introducing the other types:

**nostd::function_ref**
Not available in any standard yet.

**nostd::shared_ptr**
Concerns about ABI stability across versions for `std::shared_ptr`.

**nostd::span**
`std::span` is only available since C++20, not for previous versions.

**nostd::string_view**
`std::string_view` is only available since C++17, not for previous versions.

**nostd::unique_ptr**
Concerns about ABI stability across versions for `std::unique_ptr`.

**nostd::variant**
`std::variant` is only available since C++17, not for previous versions.

**Comment by lalitb** [comment]
Closing as we do have clarity on need for these nostd implementations,
