### ISSUE TITLE
[Metrics SDK] Use default view if no view configured for MeterProvider

### ISSUE THREAD

**Issue by lalitb** [open-telemetry/opentelemetry-cpp#1352]
As specified in SDK (https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/sdk.md#view):

> If the MeterProvider has no View registered, take the Instrument and apply the default Aggregation on the basis of instrument kind according to the [MetricReader](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/sdk.md#metricreader) instance's aggregation property.

**Comment by marcalff** [comment]
Greetings.

I think this is related:

Right now (commit 4008da54fa29c71c6e8b32d5ff7b186136a128ff), without any view,
the code end up doing this:

In:
` SyncMetricStorage::Collect()`
At:
```
  // Iterate over the unreporter metrics for `collector` and store result in `merged_metrics`
  ...
  DefaultAggregation::CreateAggregation(instrument_descriptor_)->Merge(aggregation)

```
The instrument_descriptor type is `kCounter`
The aggregation returned by `CreateAggregation` is a `LongSumAggregation`

`LongSumAggragation::Merge()` is invoked with an aggregation parameter which is a `DropAggregation`.

Inside `LongSumAggragation::Merge()`,
casting:
  `static_cast<const LongSumAggregation &>(delta)`
is invalid, leading to an exception raised by:

`nostd::get<SumPointData>((static_cast<const LongSumAggregation &>(delta).ToPoint()))`

Note that class `SyncMetricStorage` has a `create_default_aggregation_` member, initialized with
`DefaultAggregation::CreateAggregation(aggregation_type_, instrument_descriptor_)`
which takes the `aggregation_type_` into account.

`DefaultAggregation::CreateAggregation()` is used sometime with, sometime without, the aggregation type parameter in class `SyncMetricStorage`, which looks suspicious.

#1358 changes the default view to use `AggregationType::kDefault` instead of `AggregationType::kDrop`,
possibly avoiding the bad cast by default,
but I wonder if `SyncMetricStorage` should revise how to use `DefaultAggregation::CreateAggregation()` anyway,
to avoid the same bug later on different aggregations types.

Regards.

**Comment by lalitb** [comment]
> but I wonder if SyncMetricStorage should revise how to use DefaultAggregation::CreateAggregation() anyway,
to avoid the same bug later on different aggregations types.

Yes agree. Will revisit the sync flow once again to see if we can improve on the default aggregation logic.
