### ISSUE TITLE
Optionally install the header files for API, and generated targets and header files for SDK at custom/default install location.

### ISSUE THREAD

**Issue by zx8086** [open-telemetry/opentelemetry-cpp#1414]
custom/default install location?

For what ? the build, the system ?

example ?

**Comment by owent** [comment]
If you ares using cmake, you can set [CMAKE_INSTALL_PREFIX](https://cmake.org/cmake/help/latest/variable/CMAKE_INSTALL_PREFIX.html) to specify where to install all headers and library files.
If you are using bazel, there is no need to install, because all headers are auto copied by [deps](https://bazel.build/concepts/dependencies)

**Comment by zx8086** [comment]
I'm trying to instrument nginx via https://github.com/open-telemetry/opentelemetry-cpp-contrib/tree/main/instrumentation/nginx ...

Not sure what the locations should be for this given the errors are relating to missing headers.

**Comment by owent** [comment]
`cmake --install . --prefix=<installation path>` is better way. I have replied to https://github.com/open-telemetry/opentelemetry-cpp-contrib/issues/146
