### ISSUE TITLE
tsan and asan for end to end tests

### ISSUE THREAD

**Issue by esigo** [open-telemetry/opentelemetry-cpp#1669]
We should enhance our CI with asan and tsan tests for e2e tests (examples which does not have external dependency).

**Comment by lalitb** [comment]
I don't see any issue in adding these examples in CI, do you think adding unit tests with multi-threaded scenarios will also catch these race conditions?

**Comment by esigo** [comment]
That should be possible, but it will look more like e2e test I think 😉

**Comment by esigo** [comment]
Adding this to the metric GA milestone, as we have data races.

**Comment by lalitb** [comment]
> Adding this to the metric GA milestone, as we have data races.

I suspect the issue could be because observable instrument is going out of scope while we are the metric collection is happening. With infinite loop, we didn't see the issue. Can we test it by defining the observable instrument somewhere globally. This is also documented here:

https://github.com/open-telemetry/opentelemetry-cpp/blob/main/examples/metrics_simple/README.md

``
Create a Observable Counter Instrument from the Meter, and add a callback. The callback would be used to record the measurement during metrics collection. Ensure to keep the Instrument object active for the lifetime of collection.
``
