### ISSUE TITLE
How to get parent span?

### ISSUE THREAD

**Issue by VivekSubr** [open-telemetry/opentelemetry-cpp#1904]
Opentelemetry spec says it should be possible to get a parent span given a span's context:
https://github.com/open-telemetry/opentelemetry-specification/blob/v1.0.0/specification/trace/api.md#determining-the-parent-span-from-a-context

But looking at the api, there's no apparent way how to do that? There's GetParentSpanId api in SpanData, but you can only get SpanData for InMemoryExporter.

**Comment by lalitb** [comment]
The link shared talk's about getting SpanId of parent from the Context while creating a (child) span. This is supported [here](https://github.com/open-telemetry/opentelemetry-cpp/blob/d5571916e18abbd994373cdb633be0815deda319/sdk/src/trace/tracer.cc#L31) i.e., implicitly getting the span_id of parent span from the Context while creating the Span.  

The C++ implementation doesn't provide [ReadableSpan ](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/sdk.md#additional-span-interfaces) interface to get the SpanId of parent after the Span is created. This is historically by design ( to prioritize optimization over feature), and has been discussed [here](https://github.com/open-telemetry/opentelemetry-cpp/issues/1475). There is no plan to add the support.

**Comment by VivekSubr** [comment]
@lalitb : What about this api? 
auto current_ctx = opentelemetry::context::RuntimeContext::GetCurrent();

If child active span is ended, with this automatically give context of the parent span? 

If there's no way to get parent span from a span, and if you are writing a wrapper library for opentelemetry, that would force a user to keep track of parent spans right? In some sort of Stack/Queue structure.... it's things like this that caused me to hit issues like: https://github.com/open-telemetry/opentelemetry-cpp/issues/1889 and https://github.com/open-telemetry/opentelemetry-cpp/issues/1888.

**Comment by lalitb** [comment]
> If child active span is ended, with this automatically give context of the parent span?

Yes it will give the context containing parent-span once the child active span is ended. There are no getters on Span object to obtain the parent SpanId, if that is what you are looking for. I don't know how this relates to #1889 and #1888.

**Comment by VivekSubr** [comment]
@lalitb - any way to get spanId from the context returned by,
auto current_ctx = opentelemetry::context::RuntimeContext::GetCurrent();

**Comment by VivekSubr** [comment]
@lalitb - that api doesn't seem to work... once child span is ended, current span should be the parent right? I can see GetCurrentSpan() still returned that child that's been ended.

**Comment by lalitb** [comment]
Please share the code you are trying. Just ending Span::End() is not enough for context unwinding. You need to ensure that the Span object (which is of type nostd::shared_ptr) gets destroyed too.

**Comment by VivekSubr** [comment]
Your right, this works

`    auto span  = m_tracer->StartSpan("Test Span");
    auto scode = m_tracer->WithActiveSpan(span);
    auto span_id = span->GetContext().span_id();
    std::cout<<"Parent span id "<<spanId2Str(span_id)<<"\n";
    {
        auto span2  = m_tracer->StartSpan("Child Span");
        auto scode2 = m_tracer->WithActiveSpan(span2);
        auto span_id2 = span2->GetContext().span_id();

        ASSERT_EQ(span_id2, m_tracer->GetCurrentSpan()->GetContext().span_id());
         
        std::cout<<"Child span id "<<spanId2Str(span_id2)<<"\n";
        span2->End();
    }

    ASSERT_EQ(span_id, m_tracer->GetCurrentSpan()->GetContext().span_id());
    std::cout<<"span id "<<spanId2Str(m_tracer->GetCurrentSpan()->GetContext().span_id())<<"\n";     `

Must be something wrong with the way I'm using it... thank you for all the help!
