### ISSUE TITLE
Do you still use cpp_format_tools docker image?

### ISSUE THREAD

**Issue by bogdandrutu** [open-telemetry/opentelemetry-cpp#2050]
See https://github.com/open-telemetry/build-tools/tree/main/cpp_format_tools, if not please file a PR to remove it.

**Comment by lalitb** [comment]
It's not used in the CI pipeline for otel-cpp. Not sure if someone uses it locally in their setup for formatting code.

**Comment by bogdandrutu** [comment]
I will remove then :) since it is unmaintained.

**Comment by owent** [comment]
BTW: Do we have any plan to upgrade clang-format?

**Comment by marcalff** [comment]
Q: Do you still use cpp_format_tools docker image?

A: No, and it is very likely that nobody uses this for opentelemetry-cpp, because there are specific format rules for jaeger/thrift generated code that the docker image does not know about.

Opentelemetry-cpp uses this file instead:

* https://github.com/open-telemetry/opentelemetry-cpp/blob/main/tools/format.sh

See the various exceptions in the FIND command:

```
-o -name TraceLoggingDynamic.h -prune -o -name thrift-gen -prune
```

which are specific to this repository.
