### ISSUE TITLE
metrics_simple link error: undefined referrence

### ISSUE THREAD

**Issue by KSLLH** [open-telemetry/opentelemetry-cpp#2245]
**Describe your environment** Describe any aspect of your environment relevant to the problem, including your platform, build system, version numbers of installed dependencies, etc. If you're reporting a problem with a specific version of a library in this repo, please check whether the problem has been fixed on main branch.
I built opentelemetry-cpp-1.10.0 from source on Red Hat Enterprise Linux release 8.4 with manually updated linux kernel 5.12.8.
the cmake version is 3.20.2; gcc version is 8.5.0. 
Here is the dependencies versions and building instructions I used:
1. abseil-20220623:
$ mkdir build && cd build
$ cmake .. -DBUILD_SHARED_LIBS=ON \
-DABSL_BUILD_TESTING=OFF \
-DABSL_USE_GOOGLETEST_HEAD=OFF \
-DCMAKE_CXX_STANDARD=20
$ cmake --build . --target all

2. googletest-1.13.0:
$ mkdir build && cd build
$ cmake .. && cmake --build .

3. benchmark-1.7.1
$ mkdir build && cd build
$ cmake -S . -B build -DCMAKE_BUILD_TYPE=Release -DBENCHMARK_ENABLE_GTEST_TESTS=OFF
$ cmake --build build --config Release

4. protobuf-21.2
$ cmake . -DCMAKE_CXX_STANDARD=20 -Dprotobuf_INSTALL=ON -Dprotobuf_BUILD_SHARED_LIBS=ON -Dprotobuf_BUILD_TESTS=OFF
$ cmake --build . --config Release

5. grpc-1.49.2 
$ cmake -DgRPC_INSTALL=ON -DCMAKE_INSTALL_PREFIX=/usr/local/grpc-1.49.2
$ make 
$ sudo make install
After installed all the above dependencies, I build and install opentelemetry-cpp by the following instructions:
$ mkdir build && cd build
$ cmake .. -DCMAKE_POSITION_INDEPENDENT_CODE=ON \
-DBUILD_SHARED_LIBS=ON \
-DWITH_NO_DEPRECATED_CODE=ON \
-DOPENTELEMETRY_INSTALL=ON \
-DWITH_STL=ON \
-DWITH_OTLP_GRPC=ON \
-DWITH_OTLP_HRRP=ON \
-DWITH_PROMETHEUS=ON \
-DBUILDING_TESTING=OFF \
-DWITH_EXAMPLES=OFF
$ cmake --build .  --target all
$ sudo make install

**Steps to reproduce**
Describe exactly how to reproduce the error. Include a code sample if applicable.
Finally I try to directlly build the example metrics_simple from source by copy the source files metrics_ostream.cc, foo_library.cc and foo_library.h into a directory and build with the command:
$ g++ metrics_ostream.cc foo_library.cc -o metrics_simple \
-lphread -lopentelemetry_metrics \
-lopentelemetry_exporter_ostream_metrics \
-lopentelemetry_resources

**What is the expected behavior?**
What did you expect to see?

**What is the actual behavior?**
What did you see instead?
The above compiling command reports the following errors:

opentelemetry::v1::sdk::metrics::InstrumentSelectorFactory::Create(opentelemetry::v1::sdk::metrics::InstrumentType, opentelemetry::v1::nostd::string_view): undefinded referrence
opentelemetry::v1::sdk::metrics::InstrumentMeterFactory::Create(opentelemetry::v1::sdk::metrics::InstrumentType, opentelemetry::v1::nostd::string_view): undefinded referrence
collect2: error: ld returns 1

This is extremly weird to me since the libraries required for building metrics_simple are all installed, and symbols of the so called "undefined refrence" can be found in libopentelemetry_metrics.so. 

**Additional context**

**Comment by marcalff** [comment]
Thanks for the detailed report.

Given that the `libopentelemetry_metrics.so` library contains the symbols needed, I would suspect that the linker finds another copy of this library (older, without the new symbols), somewhere else on the system.

Please double check.

Side note:

```
 -DWITH_OTLP_HRRP=ON
```

This should be `WITH_OTLP_HTTP`.

**Comment by KSLLH** [comment]
@marcalff Thanks for your reply

**Comment by KSLLH** [comment]
@marcalff Thanks for your reply and correction.

I have carefully checked. There is only one copy of `libopentelemetry_metrics.so` .

**Comment by lalitb** [comment]
You may want to rule out the issue due to ordering of shared libraries provided in the command line. For reference, this is the command executed by cmake:

[ 98%] Linking CXX executable metrics_ostream_example
cd /tmp/a/opentelemetry-cpp/build/examples/metrics_simple && /usr/local/bin/cmake -E cmake_link_script CMakeFiles/metrics_ostream_example.dir/link.txt --verbose=1
/usr/bin/c++    -rdynamic CMakeFiles/metrics_ostream_example.dir/metrics_ostream.cc.o  -o metrics_ostream_example -Wl,-rpath,/tmp/a/opentelemetry-cpp/build/exporters/ostream:/tmp/a/opentelemetry-cpp/build/examples/common/metrics_foo_library:/tmp/a/opentelemetry-cpp/build/sdk/src/metrics:/tmp/a/opentelemetry-cpp/build/sdk/src/resource:/tmp/a/opentelemetry-cpp/build/sdk/src/common -lpthread ../../exporters/ostream/`libopentelemetry_exporter_ostream_metrics.so` ../common/metrics_foo_library/`libcommon_metrics_foo_library.so` ../../sdk/src/metrics/`libopentelemetry_metrics.so` ../../sdk/src/resource/`libopentelemetry_resources.so` ../../sdk/src/common/`libopentelemetry_common.so` -lpthread
make[2]: Leaving directory '/tmp/a/opentelemetry-cpp/build'
[ 99%] Built target metrics_ostream_example

**Comment by lalitb** [comment]
@KSLLH Would you like to share your findings further, Or if it is good to close this issue?
