### ISSUE TITLE
Instruments with same name but different attributes are lost

### ISSUE THREAD

**Issue by timwoj** [open-telemetry/opentelemetry-cpp#2305]
**Describe your environment** This happens on both macOS and ubuntu 22.04. I'm building against opentelemetry-cpp v1.11.0.

**Steps to reproduce**
Create two instruments the same name, but with different attributes stored in a KeyValueIterableView.

**What is the expected behavior?**
Both instruments appear in the output from the exporter, named the same but with different attributes.

**What is the actual behavior?**
Only the last instrument created shows in the output. I tested this with both the Prometheus and ostream exporters.
What did you see instead?

**Additional context**
I noticed this originally with the Prometheus exporter, because this is definitely a supported feature there. We have an existing metrics implementation that outputs something like this to Prometheus:

```
active_sessions{endpoint="",protocol="tcp"} 2 1694045963754
active_sessions{endpoint="",protocol="udp"} 1 1694045963754
```

While porting the code over to opentelemetry-cpp, only the `udp` protocol entry appears in the output from the metrics endpoint.

**Comment by lalitb** [comment]
> What is the expected behavior?
Both instruments appear in the output from the exporter, named the same but with different attributes.

Need to check this further, but don't think this should be expected behavior. Rather than allowing the creation of multiple instruments with the same name, the SDK should ideally provide a reference to the instrument that has already been created. Given that the existing API returns a unique_ptr to the instrument, this may not be feasible. An alternative approach could be to return a no-op instrument while also logging a warning for trying to create duplicate instrument.  

I may not have understood your use case, but can't you use the same instrument to record these values?

**Comment by marcalff** [comment]
Related:
* #2099

**Comment by marcalff** [comment]
In my understanding, in this case the instrumentation should:

* create a unique instrument with a name, here `active_sessions`
* report two distinct measurements from this instrument, with different attributes:
  * `active_sessions{endpoint="",protocol="tcp"} 2 1694045963754`
  * `active_sessions{endpoint="",protocol="udp"} 1 1694045963754`

Creating two instruments with the same name is an error (see #2099). It is not handled correctly right now so only the last instrument is used, but the application should nevertheless not create duplicate instruments.

**Comment by lalitb** [comment]
@timwoj - Do you have further questions on this ?

**Comment by marcalff** [comment]
Closing.

As indicated, the proper way to instrument is to have only one metric, and report multiple measurements with different attributes using the unique metric.

**Comment by timwoj** [comment]
Agreed with the closure. That description got me sorted.
