### ISSUE TITLE
Add bzlmod support

### ISSUE THREAD

**Issue by auzhva** [open-telemetry/opentelemetry-cpp#2334]
Since bazel 6.0, bazel added [bzlmod](https://bazel.build/external/overview?hl=en#bzlmod) dependency management and tracking system. Currently open telemetry is built by Bazel but is not published to the [Bazel Central Regestry](https://registry.bazel.build), which complicates importing open telemetry.

It would be awesome if open telemetry would be packaged to the BCR.

**Is your feature request related to a problem?**
Opentelemetry imports dependencies with own `opentelemetry_cpp_deps`, which is not portable to bzlmod.

**Describe the solution you'd like**
Create MODULE.bazel and publish to the BCR

**Describe alternatives you've considered**
Continue using existing, but it's... Hard...

**Comment by esigo** [comment]
@auzhva unfortunately we could not offer any official packaging.

**Comment by esigo** [comment]
@auzhva unfortunately we could not offer any official packaging.

**Comment by marcalff** [comment]
While this request makes sense, we (in opentelemetry-cpp) can not provide packaging for every build system.

The best way to address this is to make a contribution to the Bazel Central Registry directly.

**Comment by marcalff** [comment]
Added `help wanted` to advertise.

Do not prepare a PR for opentelemetry-cpp, contribute to https://registry.bazel.build/ instead.

**Comment by keith** [comment]
:wave: I submitted a PR for the modern bazel dependency management setup here:

I know there was some discussion above about submitting the config to the BCR (which I will do if this PR is merged), but my PR here is still required to modernize the bazel config in this repo.

We could also theoretically remove the old version of doing things in bazel, since right now there is some duplication, but I am initially leaving it in my PR to not affect users on older versions of bazel. I'm happy to remove it though and direct older bazel users to prior releases of this library instead if you'd prefer!

https://github.com/open-telemetry/opentelemetry-cpp/pull/2608

**Comment by keith** [comment]
still valid, linked PR should be unblocked when my other prs land
