### ISSUE TITLE
[BUILD] enum  CanonicalCode names too generic... conflict with old C defines

### ISSUE THREAD

**Issue by VivekSubr** [open-telemetry/opentelemetry-cpp#2384]
**Steps to reproduce**
We use opentelemetry together with oss-asn library: https://www.oss.com/

**What is the expected behavior?**
No Problems

**What is the actual behavior?**
CanonicalCode enums conflict with #defines in the oss C code,
```
/usr/include/opentelemetry/trace/canonical_code.h:108:3: error: expected identifier
  OUT_OF_RANGE = 11,
  ^
/usr/include/ossasn1/ossasn1.h:1696:36: note: expanded from macro 'OUT_OF_RANGE'
#define OUT_OF_RANGE               33 /* parameter value range error */

```

We've been patching CanocicalCode enums with OTEL_ prefix to get around this, ie, OTEL_OUT_OF_RANGE... but the point remains that the enum names are too generic, this can happen if someone does '#define OK 1' as well.

Proposal -> prefix OTEL_ to all the enums in CanonicalCode

**Comment by marcalff** [comment]
Thanks for the report.

From a pure technical point of view, the code polluting the namespace here is `/usr/include/ossasn1/ossasn1.h`, because it uses C preprocessor macros, what can collide with anything.

The opentelemetry-cpp code does not cause pollution, as the enums values are scoped within opentelemetry::trace, and declared as C++ enums instead of C macro defines.

Now, I do understand that the collision causes problems, and given that ASN1 is not likely to change, the opentelemetry-cpp headers will have to account for this.

`SetStatus()` used to take a `trace::CanonicalCode` a long time ago, and was changed to use a `trace::StatusCode` in this commit:

```
commit cae3511915ab907ab1f30c620b0efb2634fa5862
Author: Lalit Kumar Bhasin <labhas@microsoft.com>
Date:   Fri Jan 29 13:57:52 2021 +0530

    Update StatusCode as per specs (#535)
```

A possibility is to remove header file `opentelemetry/trace/canonical_code.h` from the code base, as enum `CanonicalCode` does no longer seem to be used anywhere.
