### ISSUE TITLE
Collect and Export metric data before PeriodicMetricReader shutdown

### ISSUE THREAD

**Issue by sfc-gh-sili** [open-telemetry/opentelemetry-cpp#2516]
Reporting the exact same issue as https://github.com/open-telemetry/opentelemetry-cpp/issues/1858

It seems that the issue was previously fixed in https://github.com/open-telemetry/opentelemetry-cpp/pull/1860, but the latest code does not have do another round of export on PeriodicMetricReader on Shutdown anymore.

**Comment by lalitb** [comment]
@sfc-gh-sili This was changed as part of #2064. You need to now call `Meterprovider::Forceflush()` before `MeterProvider::Shutdown()`. The reason is
 - It offers greater flexibility for applications that wish to shut down promptly, as the collection cycle can be time-consuming when dealing with a large number of different metrics, and they may not want to delay.
 - It aligns with the shutdown process for traces and logs. After the shutdown is initiated, any pending spans or logs are not exported.
 - The specifications do not require or mention this.

Let me know if you have any more questions.
