### ISSUE TITLE
Optimize OTLP exporter

### ISSUE THREAD

**Issue by nadiaciobanu** [open-telemetry/opentelemetry-cpp#302]
### Problem
Currently, the OTLP exporter is passed `Recordable` objects at export time. The span protobuf in the `Recordable` needs to be moved into the request that will be exported (see [`otlp_exporter.cc`](https://github.com/open-telemetry/opentelemetry-cpp/blob/ec6f70d76bd2b4c8fb8198ad852facd18afe20b6/exporters/otlp/src/otlp_exporter.cc#L29)).

Although we use `std::move` to move the span protobuf from the `Recordable` to the request, benchmark tests indicate that the protobuf is likely being *copied*, not *moved*. This is due to the way `std::move` handles const lvalue references (see this [link](https://www.nextptr.com/tutorial/ta1211389378/beware-of-using-stdmove-on-a-const-lvalue) for more information).

To see the difference between move and copy, I did the following test:

**Current code  in [`otlp_exporter.cc`](https://github.com/open-telemetry/opentelemetry-cpp/blob/ec6f70d76bd2b4c8fb8198ad852facd18afe20b6/exporters/otlp/src/otlp_exporter.cc#L29)** (probably copying, even though we're using `std::move`):
```
*instrumentation_lib->add_spans() = std::move(rec->span());
```
**Current benchmarks**:
![benchmark_copy](https://user-images.githubusercontent.com/14475923/91239332-1e1f5500-e6f4-11ea-867a-fb5f47c30204.png)

**Modified code** (swap, effectively moving):
```
instrumentation_lib->add_spans()->Swap(
        const_cast<opentelemetry::proto::trace::v1::Span *>(&rec->span()));
```
**Modified benchmarks**:
![benchmark_move](https://user-images.githubusercontent.com/14475923/91239337-237c9f80-e6f4-11ea-8c1d-0f894555a481.png)

We can see that the benchmarks are roughly half for the modified code (500 ns vs. 1000 ns for dense spans).

### Solution
The modified code above is unsafe, since it uses a `const_cast`.

Another solution is to modify the `Recordable` class to store a pointer to a span protobuf, instead of a span protobuf object.

The exporter could maintain a collection of the actual span protobufs. When it becomes time to export, the exporter could associate each given `Recordable` with its span protobuf using the span id. Storing span protobufs in the exporter, rather than in `Recordable`,  would likely allow the protobufs to be moved into the requests, rather than copied.

**Comment by IlyaKobelevskiy** [comment]
Thanks for bringing up this issue! I have a followup idea of how to simplify implementation.

std::move in current implementation makes a copy because it attempts to move a const ref: [const proto::trace::v1::Span &](https://github.com/open-telemetry/opentelemetry-cpp/blob/ec6f70d76bd2b4c8fb8198ad852facd18afe20b6/exporters/otlp/include/opentelemetry/exporters/otlp/recordable.h#L15), which ends up in a copy. 

Instead of storing a naked pointer in Recordable and maintaining collection of actual protos in exporter, we can simply
modify [oltp::Recordable](https://github.com/open-telemetry/opentelemetry-cpp/blob/ec6f70d76bd2b4c8fb8198ad852facd18afe20b6/exporters/otlp/include/opentelemetry/exporters/otlp/recordable.h#L12) interface to add a non-const Swap method to its public interface that would allow Swapping contents of stored Span with another Span.
This might be simpler then storing a pointer and object itself in Exporter, and should achieve same performance boost as illustrated in this example.

Please note that const_cast as used in the example is technically an undefined behavior, but I think here it correctly estimates the expected performance boost.
