### ISSUE TITLE
gRPC version prompt

### ISSUE THREAD

**Issue by michaelchao** [open-telemetry/opentelemetry-cpp#3057]
I'm now using otel-cpp with gRPC, however compile failed, I don't now what version of gRPC should I use. SI I recommend adding version required infomation for gRPC in README.

**Comment by owent** [comment]
We support many versions of gRPC, which one to use depends on your build system.
If you do not use gRPC before, here is a recommend versions of depended packages: <https://github.com/open-telemetry/opentelemetry-cpp/blob/main/third_party_release>

**Comment by marcalff** [comment]
As @owent described:

* opentelemetry-cpp does not require a specific version of grpc. Instead, the model is that opentelemetry-cpp uses the version of grpc that might be already used by the application, due to other dependencies.
* If there are no reasons to use a specific version, a good choice is to pick the version used in CI tests. Currently, this is gRPC=v1.49.2, per the third_party_release file.

Accepting this report as a documentation issue, so that the README or related doc mention clearly where to find the current information for each dependency.

**Comment by michaelchao** [comment]
Tks all suggestions

**Comment by michaelchao** [comment]
Ths, done
