### ISSUE TITLE
Consistent namespace scope resolution 

### ISSUE THREAD

**Issue by xyira** [open-telemetry/opentelemetry-cpp#368]
As suggested in this [comment](https://github.com/open-telemetry/opentelemetry-cpp/pull/363#discussion_r505600440), the scope resolution usage should be consistent across all files. A convention should be established to use either `opentelemetry::*` or simplified to `*`. This should be done across all files and namespaces. 

cc @alolita

**Comment by PaurushGarg** [comment]
@lalitb @pyohannes : Can I please pick this issue. please assign this to me, I am working in @alolita  team. 
Tag @alolita

**Comment by lalitb** [comment]
@PaurushGarg  - yes this would be really good to fix. It would also be good to follow the namespace guidelines from here:
https://google.github.io/styleguide/cppguide.html#Namespaces
 Basically
 - You may not use a using-directive to make all names from a namespace available.
 - Do not use Namespace aliases at namespace scope in header files except in explicitly marked internal-only namespaces, because anything imported into a namespace in a header file becomes part of the public API exported by that file.

Also in source files, we need to have consistent namespace alias names  ( eg, `trace_sdk`, `trace_api`, `nostd` etc ).
