### ISSUE TITLE
Clarify ABI requirements for the exporter interface

### ISSUE THREAD

**Issue by pyohannes** [open-telemetry/opentelemetry-cpp#43]
_This is intended for continuing the discussion we had in the meeting on March 2nd._

The SDK user must be able to register span processors on the `TraceProvider`. Several span processors (and thus several exporters) can be registered at the same time. The SDK must allow users to implement and configure custom processors (and, obviously exporters).

Usually, exporters and other user defined objects will be located in a separate binary. Those binaries could either be linked statically with the SDK or dynamically loaded into the same process as the SDK.

For dynamically loaded exporter binaries, we have to decide how to define ABI requirements, similar to the API part of OpenTelemetry C++.

The main possibilities I see:

####  No ABI requirements are defined

In this case, the user has to take care that the SDK and the exporter binary are compatible. When using the standard SDK provided by OpenTelemetry C++, the user always has the possibility to compile the SDK in a way that is compatible with the exporter binary.

#### The same ABI requirements as for the API apply

This would restrict us in defining and changing the interface. However, in that scenario users would have the possibility to combine pre-compiled SDKs and exporter binaries that were compiled with different STL versions.

For reference, here's the [related section in the spec](https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/sdk-tracing.md#span-exporter), and here's a [sketch of a C++ span exporter interface](https://github.com/pyohannes/opentelemetry-cpp/blob/exporter-interface/sdk/include/opentelemetry/sdk/trace/exporter.h).

**Comment by pyohannes** [comment]
I'm not sure about all the use cases out there. I think providing a way to dynamically load an exporter, but without imposing ABI requirements (thus imposing the burden of ensuring compatibility to the user) seems feasible to me.

**Comment by rnburn** [comment]
What if we build out the exporter interface and have something like DynamicallyLoadedExporter as a special case of an exporter?

As far as the interface sketch,
```
Export(
      std::vector<std::unique_ptr<opentelemetry::trace::Span>> &spans
```
trace::Span is the caller interface to a span -- but that's not what the exporter has access to, right?

Also, why use an owning std::vector type instead of exporting by just pointing to the area in memory that holds buffered spans?

**Comment by pyohannes** [comment]
You're right for sure, I just used the sketched interface to make some experiments with span processors.

That might be better, provided we have a `SpanData` interface:
```c++
Export(
      nostd::unique_ptr<opentelemetry::sdk::trace::SpanData>* spans, size_t numSpans) 
```

And would even be ABI stable, provided that `SpanData` has a stable ABI.

**Comment by rnburn** [comment]
I was hoping with to have a Recordable abstraction that avoids using SpanData in the interface.

It can be expensive to build up a SpanData representation. In our benchmarking, we've gotten around a 5x improvement in some cases by using direct serialization instead of something like SpanData.

But here's how I was think it would work.

1. An Exporter has a mechanism to create a Recordable (e.g. a MakeRecordable method).
2. The Recordable is ABI stable and hooks into span events. I already started to fill parts of it out [here](https://github.com/rnburn/opentelemetry-cpp/blob/recorder-interface/sdk/src/trace/recordable.h).
3. If an exporter does want to translate and build on top of SpanData, there can be a common SpanData Recordable.
```
class SpanData final : public Recordable {
};
```
that has accessor methods
```
for (auto& tag : span_data.tags()) {
    // ...
}
```
4. In MakeRecordable, the exporter returns the SpanData. And when Export gets called, it can cast the provided Recordables back to SpanData.
```
auto span_data = static_cast<SpanData*>(recodable);
```

Also, because only the exporter side needs to interface with a SpanData, there's no need to make it ABI stable. (Only the Recodable interface needs to be ABI stable).

And Exporters that want better performance could provide their own Recordables.

**Comment by pyohannes** [comment]
I understand the performance concerns, thanks for explaining. This makes sense to me, as long as there's the spec conformant way for vendors to write exporters receiving `SpanData` like objects. In addition to a more performant `Recordable` way.

One thing that's not yet clear to me is how the `Recordable` approach works when using several exporters at the same time, each providing a different `Recordable`. Would a span need a list of `Recordable` objects?

**Comment by rnburn** [comment]
A Recorder can make a chained Recordable.

```
class ChainedReordable final : public Recordable {
   // ...
  private:
    std::vector<std::unique_ptr<Recordable>> recordables_;
}
```
that forwards methods to all Recordables in the chain.

Then when a Span finishes the Recordable, it can be de-chained and sent to the separate Exporters.

**Comment by pyohannes** [comment]
I see, I think this also would go hand-in-hand with a `ChainedRecorder`.

Thanks for the explanations, I understand the design now and I see how it can co-exist with a parallel SpanData approach.

**Comment by reyang** [comment]
discussed during the community meeting, no need to bring ABI for exporter API for now.

**Comment by eyakimov-bbg** [comment]
Please keep this open until we update documentation to explicitly state that "SDK does not currently provide ABI compatibility"

**Comment by pyohannes** [comment]
The conclusions of this discussion were added to the [documentation](https://github.com/open-telemetry/opentelemetry-cpp/pull/70).
