### ISSUE TITLE
Allow Bazel to consume opentelemetry-cpp via http_archive against github's auto-zip feature

### ISSUE THREAD

**Issue by bogdandrutu** [open-telemetry/opentelemetry-cpp#461]
**Describe your environment** Describe any aspect of your environment relevant to the problem, including your platform, build system, version numbers of installed dependencies, etc. If you're reporting a problem with a specific version of a library in this repo, please check whether the problem has been fixed on master.

Trying to use this library using bazel from a third-party repository.

**Steps to reproduce**

Just add dependency to the library:

```
# Load OpentTelemetry-CPP dependency
http_archive(
    name = "com_github_opentelemetry_cpp",
    strip_prefix = "opentelemetry-cpp-7d7bd5247f0b546cb674afd82a6ef57be91a83d1",
    sha256 = "a2940df54fb0087715f96e4cb6c860987a3141100fb27fcf0871fe2638c82f7e",
    urls = [
        "https://github.com/open-telemetry/opentelemetry-cpp/archive/7d7bd5247f0b546cb674afd82a6ef57be91a83d1.tar.gz",
    ],
)
```

**What is the expected behavior?**
What did you expect to see?

I expect build to work.

**What is the actual behavior?**
What did you see instead?

Error because `@com_github_opentelemetry_proto` repository is not defined, I need to manually define it:

```
ERROR: /private/var/tmp/_bazel_lazy/26fe0d78ac6895853b1f61b132156f0e/external/com_github_opentelemetry_cpp/exporters/otlp/BUILD:34:11: @com_github_opentelemetry_cpp//exporters/otlp:otlp_exporter depends on @com_github_opentelemetry_proto//:trace_service_grpc_cc in repository @com_github_opentelemetry_proto which failed to fetch. no such package '@com_github_opentelemetry_proto//': Unable to load package for //bazel:opentelemetry_proto.BUILD: not found.
```

```
http_archive(
        name = "com_github_opentelemetry_proto",
        build_file = "@com_github_opentelemetry_cpp//bazel:opentelemetry_proto.BUILD",
        sha256 = "08f090570e0a112bfae276ba37e9c45bf724b64d902a7a001db33123b840ebd6",
        strip_prefix = "opentelemetry-proto-0.6.0",
        urls = [
            "https://github.com/open-telemetry/opentelemetry-proto/archive/v0.6.0.tar.gz",
        ],
)
```

**Additional context**

In the bazel config it is recommended to use repository definition that do not depend on gitsubmodules because those are transitively working when depending on the main target only.

**Comment by jsuereth** [comment]
FYI - The issue here is that "HTTP ARCHIVE" does not work with git submodules.  It relies on github to create a TAR file of all the source code necessary to build the project, but this does NOT pull down submodules.

There are two possible solutions:

1. We can create our own .tar.gz files when pushing tagged releases for consumption that are Bazel HTTP friendly.
2. We do not use any git submodules within bazel builds and find an alternative way to keep `cmake` and `bazel` dependency versions in sync.

**Comment by jsuereth** [comment]
Also relevant: https://github.com/dear-github/dear-github/issues/214

**Comment by jsuereth** [comment]
Also: https://stackoverflow.com/questions/12936014/include-a-github-submodule-automatically-in-download

**Comment by maxgolov** [comment]
We also need to consider what happens if some `custom` exporters get moved to `contrib/exporters` - which is easy to pull with a submodule, e.g. Elastic - used by many; or ETW - would be used by anything that ever relies on ETW, e.g. all Microsoft products, and assuming that Google has https://github.com/google/UIforETW - there are products, e.g. Chromium on Windows, that would use ETW for some flows.... Then how do we pull this in Bazel - can Bazel overlay two archives one over another while building, or how does that work for a Bazel build of SDK that includes `custom` / `vendor` stuff from `contrib`?

> We do not use any git submodules within bazel builds and find an alternative way to keep cmake and bazel dependency versions in sync.

^ this totally makes sense to me. We should have a markdown document that maps between Bazel deps versions and submodule branch+commitid/tag for CMake with recursive submodules, maybe with a script that enforces a change to that document whenever we detect a change to bazel build deps or to submodule commit IDs.

**Comment by maxgolov** [comment]
..or maybe we should not be in a rush to move custom vendor stuff to `contrib`, and use `CODEOWNERS` files instead, keeping most stuff in the main repo.

**Comment by alolita** [comment]
@jsuereth: action - will be looking at this issue for Bazel.

**Comment by bogdandrutu** [comment]
@jsuereth I think this is now completed, I was able to build everything using bazel from an external repo and did not have to use git submodules for this project 💯
