### ISSUE TITLE
Move ElasticSearch  exporter to contrib repo

### ISSUE THREAD

**Issue by lalitb** [open-telemetry/opentelemetry-cpp#489]
As per the opentelementry lanaugage [guidelines](https://github.com/open-telemetry/opentelemetry-specification/blob/f081ad568379c4c56f9cacfff70d88dd9b23a725/specification/library-guidelines.md#requirements), only specific set of exporters should be part of SDK implementation : 
* Jaeger.
* Zipkin.
* Prometheus.
* OpenTelemetry Protocol (when the protocol is specified and approved).
* Standard output (or logging) to use for debugging and testing as well as an input for the various log proxy tools.
* In-memory (mock) exporter that accumulates telemetry data in the local memory and allows to inspect it (useful for e.g. unit tests).
[Elastic Search exporter](https://github.com/open-telemetry/opentelemetry-cpp/tree/master/exporters/elasticsearch) should hence be moved out to [contrib ](https://github.com/open-telemetry/opentelemetry-cpp-contrib) repo.

**Comment by maxgolov** [comment]
Guidelines also say: "...should be placed elsewhere (**the exact approach for storing and maintaining vendor-specific exporters will be defined in the future**).", without actually saying that we should move to contrib. There is an OTEP https://github.com/open-telemetry/oteps/issues/142 , but no conclusion other than: "**Consider having CODEOWNERS for specific exporters**" answer having the most upvotes.

We discussed on a few calls before that for now any custom exporter we work on, may as well have the `CODEOWNERS` file rather than forcing the move into, effectively limbo - unapproved location that may be subject to change? That is how I read "**approach will be defined in the future**". `CODEOWNERS` file in the main repo solves this today in predictable fashion, without waiting for non-deterministic amount of time for non-deterministic outcome.

**Comment by lalitb** [comment]
Closing this based on above comments.
