### ISSUE TITLE
Make ext.http.curl.BasicCurlHttpTests.RequestTimeout optional in test run?

### ISSUE THREAD

**Issue by ThomsonTan** [open-telemetry/opentelemetry-cpp#499]
It seems the test `ext.http.curl.BasicCurlHttpTests.RequestTimeout` could take significant time for timeout in the total test running process. This slows local development process as the test is usually expected to complete in 1 minute.

```
        Start 347: ext.http.curl.BasicCurlHttpTests.RequestTimeout
347/349 Test #347: ext.http.curl.BasicCurlHttpTests.RequestTimeout ....................................................   Passed  132.83 sec
```

**Comment by lalitb** [comment]
This fix to use the same timeout interval for connection and response is as part of this PR  : https://github.com/open-telemetry/opentelemetry-cpp/pull/448/files#diff-34bb57227130d5826d6aae04c708dcd9c8adf500b365a4bfb0b6e5d02fc6d275R193.

Since there are other discussions in this PR, I will create separate small PR for the fix.

**Comment by ThomsonTan** [comment]
Is the current default timeout 5 seconds? Seems the waiting I got is much longer than that.

**Comment by lalitb** [comment]
Yeah, current 5 sec timeout is only used for receiving response from server, and not while creating connection. As we are not overriding the timeout to create connection, it uses the default timeout provided by libcurl ( which is 5 mins ):

https://github.com/curl/curl/blob/df1240ccac9b6efc86213161ee242f3118392fa1/lib/connect.h#L43

The above PR fixes this - ie using the same timeout value ( 5 secs ) for both connection creation and response receiving.
