### ISSUE TITLE
Convert all TODOs in source files to Github issues?

### ISSUE THREAD

**Issue by ThomsonTan** [open-telemetry/opentelemetry-cpp#604]
TODOs in source files could be missed for tracking and triaging. I propose to convert all of them to Github issues. Let me know your thoughts.

**Comment by maxgolov** [comment]
I think it's very good intention. However, this may create another hassle, i.e. when you know that something could have been done better. But it's not _very important_ , then instead of flagging it in code - you'd keep back and never disclose.. Most IDEs (Visual Studio, Eclipse) also have a way of finding all tags, such as `XXX` or `TODO` or `FIXME`, and listing them in a flat list. If you do that quick search on any big codebase, e.g. Chromium - proof link: https://github.com/chromium/chromium/search?l=C&q=TODO , you'd see 19 pages of places in code where they used `TODO` 😺  .. sigh. It's an old practice, some just got used to that. `XXX` - just 5 pages, and `FIXME` - is 50 pages.

**Comment by maxgolov** [comment]
I think well-weighted approach may include both -- something like what Chromium does:

```cpp
// TODO(https://crbug.com/958675): In theory, it should be possible to use just...
…
```

That way even if GitHub issue gets closed due to inactivity, the item remains in code. It's easier to spot some caveat while looking in code rather than searching for GitHub issues.

**Comment by pyohannes** [comment]
I think a combined approach is ok.

However again: I think we can automatically close PRs due to inactivity, but I don't think we should never close issues due to inactivity.

**Comment by maxgolov** [comment]
Depends on how many issues we have in our backlog that are _lower-priority_ , at some point we may need to resort to using an auto-closure bot.

**Comment by lalitb** [comment]
There are 77 TODOs in code, major components are:
```
$ grep -r TODO * | grep -v tools |  grep -v nostd | wc -l
77
$ grep -r TODO * | grep -v tools |  grep -v nostd | grep -i jaeger | wc -l
11
$ grep -r TODO * | grep -v tools |  grep -v nostd | grep -i etw | wc -l
20
$ grep -r TODO * | grep -v tools |  grep -v nostd | grep -i http | wc -l
8
$ grep -r TODO * | grep -v tools |  grep -v nostd | grep -i sdk | wc -l
12
$ grep -r TODO * | grep -v tools |  grep -v nostd | grep -i api | wc -l
8
```
Moving this to 1.0.0 milestone - to access each TODO, and create issues for relevant ones.
