### ISSUE TITLE
Only support signed 64 bit integers as attribute values

### ISSUE THREAD

**Issue by pyohannes** [open-telemetry/opentelemetry-cpp#634]
For attribute values, the [specification ](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/common/common.md#attributes) only asks for one integer value: signed 64 bit integers.

However, currently our API currently supports [four integer types](https://github.com/open-telemetry/opentelemetry-cpp/blob/main/api/include/opentelemetry/common/attribute_value.h#L15):
* `uint32_t`
* `uint64_t`
* `int32_t`
* `int64_t`

OTLP also [only supports signed 64 bit integers](https://github.com/open-telemetry/opentelemetry-proto/blob/main/opentelemetry/proto/common/v1/common.proto#L33), so we will run into problems with unsigned 64 bit integers there.

I recommend aligning with the specification and to only support `int64_t`. I can put up a PR for that, but this is breaking change, so please give your opinions here.

**Comment by maxgolov** [comment]
I think this is a disaster in the making.

**Comment by maxgolov** [comment]
Let me elaborate: certain metrics flows rely on unsigned 64-bit integers. Most mature tracing systems support the full gamut of types. It is always easy to violently convert any other type to `int64_t` for OTLP exporter, if that is the only type to be supported by OTLP exporter, but it is much harder to get back and reconstruct unsigned 64-bit integer from `int64_t`  if typing information is lost right away on API surface.

**Comment by maxgolov** [comment]
Also narrowing it down to just `int64_t` - will present ABI compatibility challenge later on for C++ API, should any of these other types get added in future. I think from the language perspective and from the future-proofing perspective - you still have to accept `Integral` or `Float` type on API surface. No matter what number type it is on API surface. Then convert it to whatever is the type supported by concrete exporter... And if concrete exporter cannot express unsigned 64-bit integers - I guess then someone can come up with an exporter that converts a `large number` to `string`, and append some relevant type-hinting attribute fields, that declare that, indeed, my `Payload["myNumber"]="0xFFFFFFFFFFFFFF"` is indeed `Payload["myNumber.Type"]="uint64_t"` or alike...

From ETW exporter perspective that supports much wider typing system (and subsequently many other databases that may store strongly typed key-value pairs), I'd say that restricting this to just `int64_t` on API surface would be a mistake.

**Comment by lalitb** [comment]
Agree @maxgolov  typing information could to relevant to many telemetry systems, and loosing this at api level won't be good. As you mentioned, we need to find ways to preserve type in such scenarios.

**Comment by maxgolov** [comment]
@pyohannes - makes sense to me!  We can ensure that we add a snippet to our documentation, something like: "**Please make sure that the value types passed to attributes are compatible with your exporter. Default OTLP exporter implementation allows for the following types (link) ... API surface enables type casting, as in changing an variable of one data type into another when and if it makes sense. For example, 32-bit signed integers passed to API may be transformed to 64-bit signed integers. However, unsigned 64-bit integers are not supported by OTLP exporter. Please avoid passing types that are not compatible with the exporter of your choice.**"

**Comment by maxgolov** [comment]
https://github.com/open-telemetry/opentelemetry-specification/issues/780

**Comment by lalitb** [comment]
Does it mean that we would keep supporting all the types for attribute values at api surface, and let exporter decide how to handle these data? Won't that be non-compliance with api specs ?

**Comment by maxgolov** [comment]
> Won't that be non-compliance with api specs ?

We can provide the list of types that are supported by OTLP exporter. And explain that any 'non-standard' type behavior is `reserved for future use` , due to unique ABI compatibility requirements of native code (other languages generally do not have these strict requirements).

I promised to follow-up with the list of practical reasons to advocate for inclusion of:
- `uint64_t` type; and 
- - byte array` type.

These are the reasons:

1. [DTrace](https://en.wikipedia.org/wiki/DTrace) is a prominent trace framework for Sun, Mac and Microsoft maintains a port of it for Windows and Linux. DTrace supports the wide gamut of types, specifically the entirety of Integer primitive types, as well as byte buffer arrays. So one designing a shim / exporter from DTrace traces to OpenTelemetry should take that into consideration.

2. [Google API Discovery Service](https://developers.google.com/discovery/v1/type-format) contains a good list of types. And what happens to the types if they cannot be natively expressed in JSON notation, for example. Nevertheless, there is an assumption that APIs may express their parameters as `uint64_t`. If you are designing an APM solution that is expected to trace API calls, that APM solution should respect the wide gamut of types. For example, `span->AddEvent({{"call", "MyAPICallWithUint64Param"}, {"uint64key", 0xFFFFFFFFFFFFFFFF}})` - is a valid construct in scope of APM. Without that construct we are inherently unable to trace the API calls properly.

3. In embedded engineering, e.g. CPU performance counters on ARM architecture, are 64-bit wide, not negative. If one to design a solution that tracks the counter value in _native code_ , it has to respect the fact that it would largely deal with unsigned 64-bit integers.

4. Android Tracing framework. [Source code here](https://cs.android.com/android/platform/superproject/+/master:system/core/libcutils/include/cutils/trace.h;l=216) relies on `uint64_t` _tags_. These do not directly map to concept of `SpanId` or `TraceId`. And the actual _unsigned_ value of these tags should be respected in E2E APM system, esp if it needs to deal with Mobile Observability scenarios.

I would say we should `future-proof it`, by describing that the extra types are `reserved for future use`. That is not non-compliance, in my opinion. Even in C++ standard you can have `non-standard` extensions, that does not mean you are `non-compliant` by providing an extension to the basic set of requirements.

I hope we can get the byte arrays support added in the nearest update of spec, e.g. in `v1.1`, as I believe `8-bit byte buffers` telemetry is a fundamental feature of most other telemetry flows. It certainly is also a basic feature in both - Event Tracing for Windows, as well as in [LTTNG](https://lttng.org/man/3/lttng-ust/v2.12/).
