### ISSUE TITLE
Add TraceState to recordable interface

### ISSUE THREAD

**Issue by lalitb** [open-telemetry/opentelemetry-cpp#661]
TraceState information is required by otlp exporter (and possibly others ) and should be made available through Recordable Interface.

https://github.com/open-telemetry/opentelemetry-proto/blob/4a2aefa60114914fa7f2acd40ab376c9fc1f1e19/opentelemetry/proto/trace/v1/trace.proto#L81

Once this if fixe, TODO from below can be removed:
https://github.com/open-telemetry/opentelemetry-cpp/blob/85d306f124b95c6935ecbd7c0f9e5662f76b9c21/exporters/otlp/src/recordable.cc#L166

**Comment by eyjohn** [comment]
I was looking into this and the following question came up:

Should we consider TraceState on par with TraceId/SpanId/ParentSpanId as per https://github.com/open-telemetry/opentelemetry-cpp/blob/7a0745de876dee7f2c137f61daa906c4c95d359f/sdk/include/opentelemetry/sdk/trace/span_data.h#L174 . I somewhat consider that trace_state is somewhat of an "identifying" property of the span that is immutable following creation. Therefore I'm considering refactoring `SetIds(trace_id, span_id, parent_id)` to `SetIdentity(trace_id, span_id, parent_id, trace_state)`. We could go with a second method, but I feel like they would always be called together, e.g. right after here: https://github.com/open-telemetry/opentelemetry-cpp/blob/7a0745de876dee7f2c137f61daa906c4c95d359f/sdk/src/trace/span.cc#L89

If any one has any views on this, please share them, otherwise, I'm going to go ahead and switch to `SetIdentity` as described above.

**Comment by pyohannes** [comment]
Just a thought. What about having two methods:
```c++
void SetSpanContext(const SpanContext& context);
void SetParentId(const SpanId& parentSpanId);
```

Or just putting them into one method. I think passing the whole `SpanContext` will guard us against future requests (for `trace_flags` or `IsRemote`).

**Comment by eyjohn** [comment]
Yup sounds better, I'll go with `SetIdentity(const SpanContext& sc, SpanId parent);`

As for the SpanData, I was thinking the mirrored interface(s) broken up as
- `GetSpanContext()`
- `GetParentSpanId()`

Any need to keep the old accessors for TraceId/SpanId around? I can remap them to read from the held SpanContext or just drop them altogether.
