### ISSUE TITLE
Not able to find PrometheusExporter class in Prometheus Exporter

### ISSUE THREAD

**Issue by debasis09** [open-telemetry/opentelemetry-cpp#908]
There are documentation available in the net that we need PrometheusExporter class object to Export the metrics which will be scraped by Prometheus server.
Even found the sample code like

address = "localhost:8080";
PrometheusExporter exporter{address};
//.......prepare metrices then
exporter.Export(collection);

But when I downloaded the opentelemetry-cpp repo I did not find any prometheus_exporter.h or prometheus_exporter.cc in the repo.

Can you plz tell me where to find PrometheusExporter class or how to export the "collection" without PrometheusExporter class.

**Comment by lalitb** [comment]
Prometheus Exporter is incomplete ( see PR : https://github.com/open-telemetry/opentelemetry-cpp/pull/263). The metrics specs have been reworked since the exporter work was done, and most of the metrics C++ code would need a rewrite. Would suggest you not use the current code. Will close this ticket.

**Comment by debasis09** [comment]
Thanks for your response. I just would like to ask that did you mean the complete Prometheus Exporter code inside "exporters/prometheus/" I should not use for my application?

**Comment by lalitb** [comment]
Yes, the current implementation is incomplete, and it will change in the future to align with the updated metrics specs.
