### ISSUE TITLE
detail namespace should be kept compatible or denoted as internal-only usage

### ISSUE THREAD

**Issue by jsuereth** [open-telemetry/opentelemetry-cpp#972]
There's a few undocumented "detail" namespaces.  I'm assuming these are meant to be "changeable" header-only implementation components we don't want to maintain 100% compatibility for.

Here's an [example](https://github.com/open-telemetry/opentelemetry-cpp/blob/main/api/include/opentelemetry/trace/span_context_kv_iterable_view.h)

All such "detail" namespaces should have documentation denoting these are internal-only packages (or we need to commit to not changing any interface exposed here).

Additionally, can also document this [here](https://github.com/open-telemetry/opentelemetry-cpp/blob/main/Versioning.md#versioning)

**Comment by lalitb** [comment]
> There's a few undocumented "detail" namespaces. I'm assuming these are meant to be "changeable" header-only implementation components we don't want to maintain 100% compatibility for.

Anything under the `::detail` namespace under `api` folder is used internally within `api`, and not supposed to be used outside. Will add documentation for all functionality within this `namespace`.

**Comment by lalitb** [comment]
Actually, we already exclude all functionality under `detail` namespace from public API [documentation ](https://opentelemetry-cpp.readthedocs.io/en/latest/) as below:

https://github.com/open-telemetry/opentelemetry-cpp/blob/main/docs/public/Doxyfile#L846:L851

And in that case I feel we don't need to document individual files as `internal` api. I have raised small PR #973 to exclude missing header files. Please let us know if you think otherwise.

**Comment by ThomsonTan** [comment]
@lalitb do you think `detail` could be renamed to `internal` to express the namespace is not for public API?

**Comment by lalitb** [comment]
> do you think detail could be renamed to internal to express the namespace is not for public API?

@ThomsonTan - use of `detail` namespace is common in C++ codebase for this purpose. Eg, `boost` library uses it to hide internal functionality.
